import { Hono } from "hono";
import type { SessionUser } from "../services/auth.service";
import { Layout } from "../components/Layout";
import { todayIso } from "../utils/dates";
import { createRecord, deleteRecord, getRecordForTeacher, listActiveStudentsForTeacher, listRecords, listTeachingClasses, listVisionValues, monthlyRecap, saveNarrative, semesterRecap, updateRecord } from "../services/anecdotal.service";

type AppContext = { Variables: { user: SessionUser } };
export const anecdotalRoutes = new Hono<AppContext>();
const locations = ["Kelas", "Halaman/lapangan", "Kantin", "Perpustakaan", "Luar kelas - kegiatan"];
const followUps = ["Apresiasi lisan", "Bimbingan pribadi", "Komunikasi ke orang tua", "Teguran ringan", "Perlu pemantauan lanjutan"];
const ids = (value: unknown) => (Array.isArray(value) ? value : value ? [value] : []).map(Number).filter(Number.isInteger);
const str = (value: unknown) => String(value ?? "").trim();

function JournalTabs({ active }: { active: "teaching" | "anecdotal" }) {
  const tabClass = "inline-flex items-center px-3 py-2 whitespace-nowrap";
  return <div class="flex gap-2 mb-5 text-sm overflow-x-auto no-scrollbar"><a href="/app/journal" class={`${tabClass} ${active === "teaching" ? "gt-btn-primary" : "gt-btn-secondary"}`}>Jurnal Mengajar</a><a href="/app/journal/anecdotal" class={`${tabClass} ${active === "anecdotal" ? "gt-btn-primary" : "gt-btn-secondary"}`}>Anecdotal Record</a></div>;
}

function RecordForm({ action, classes, students, values, record }: { action: string; classes: any[]; students: any[]; values: any[]; record?: any }) {
  const selected = new Set(record?.values?.map((value: any) => value.visionValueId) ?? []);
  return <form method="post" action={action} class="gt-card p-4 space-y-4">
    {!record && <label class="block"><span class="gt-label">Kelas</span><select name="classId" class="gt-input" onchange="window.location.href='/app/journal/anecdotal/new?classId='+this.value"><option value="">Pilih kelas</option>{classes.map((item) => <option value={item.id}>{item.name}</option>)}</select></label>}
    <label class="block"><span class="gt-label">Murid</span><select name="studentId" required class="gt-input"><option value="">Pilih murid</option>{students.map((student) => <option value={student.id} selected={record?.studentId === student.id}>{student.name}{student.nis ? ` · ${student.nis}` : ""}</option>)}</select></label>
    <div class="grid grid-cols-2 gap-2"><label class="block"><span class="gt-label">Tanggal kejadian</span><input type="date" name="eventDate" value={record?.eventDate ?? todayIso()} required class="gt-input" /></label><label class="block"><span class="gt-label">Jam (opsional)</span><input type="time" name="eventTime" value={record?.eventTime ?? ""} class="gt-input" /></label></div>
    <label class="block"><span class="gt-label">Lokasi</span><input name="location" list="locations" value={record?.location ?? ""} placeholder="Pilih atau isi sendiri" class="gt-input" /><datalist id="locations">{locations.map((item) => <option value={item} />)}</datalist></label>
    <label class="block"><span class="gt-label">Deskripsi peristiwa</span><textarea name="description" rows={4} required class="gt-input">{record?.description ?? ""}</textarea></label>
    <fieldset><legend class="gt-label">Kategori</legend><div class="flex gap-2"><label class="gt-card px-3 py-2 text-sm"><input type="radio" name="category" value="positive" required checked={record?.category === "positive"} /> Positif</label><label class="gt-card px-3 py-2 text-sm"><input type="radio" name="category" value="needs_guidance" required checked={record?.category === "needs_guidance"} /> Perlu bimbingan</label></div></fieldset>
    <fieldset><legend class="gt-label">Nilai visi terkait (minimal 1)</legend><div class="flex flex-wrap gap-2">{values.map((value) => <label class="gt-card px-3 py-2 text-sm"><input type="checkbox" name="visionValueIds" value={value.id} checked={selected.has(value.id)} /> {value.name}</label>)}</div></fieldset>
    <label class="block"><span class="gt-label">Tindak lanjut (opsional)</span><input name="followUpNotes" list="follow-ups" value={record?.followUpNotes ?? ""} placeholder="Pilih atau isi sendiri" class="gt-input" /><datalist id="follow-ups">{followUps.map((item) => <option value={item} />)}</datalist></label>
    <button class="gt-btn-primary w-full py-2.5">Simpan catatan</button>
  </form>;
}

anecdotalRoutes.get("/app/journal/anecdotal", async (c) => {
  const user = c.get("user"); const classId = Number(c.req.query("classId")) || undefined; const month = c.req.query("month") || todayIso().slice(0, 7);
  const [classes, records] = await Promise.all([listTeachingClasses(user.id), listRecords(user.id, { classId, month })]);
  const unobserved = classId
    ? (await listActiveStudentsForTeacher(user.id, classId)).filter((student) => !records.some((record) => record.studentId === student.id))
    : [];
  return c.html(<Layout title="Anecdotal Record" user={user} activeNav="journal"><JournalTabs active="anecdotal" /><div class="flex items-center justify-between gap-3 mb-3"><div><h1 class="text-xl font-semibold">Anecdotal Record</h1><p class="gt-muted text-sm">Catatan observasi harian murid</p></div><a href={`/app/journal/anecdotal/new${classId ? `?classId=${classId}` : ""}`} class="gt-btn-primary inline-flex items-center px-3 py-2 text-sm whitespace-nowrap">+ Catatan</a></div><form method="get" class="grid grid-cols-2 gap-2 mb-4"><select name="classId" class="gt-input" onchange="this.form.submit()"><option value="">Semua kelas</option>{classes.map((item) => <option value={item.id} selected={item.id === classId}>{item.name}</option>)}</select><input type="month" name="month" value={month} class="gt-input" onchange="this.form.submit()" /></form>{classId && unobserved.length > 0 && <div class="gt-card p-3 mb-4 text-sm"><b>Pengingat: {unobserved.length} murid belum tercatat bulan ini.</b><p class="gt-muted mt-1">{unobserved.map((student) => student.name).join(", ")}</p></div>}<div class="flex gap-3 text-sm mb-4"><a class="gt-link-muted" href={`/app/journal/anecdotal/recap/monthly?classId=${classId ?? ""}&month=${month}`}>Rekap bulanan</a><a class="gt-link-muted" href={`/app/journal/anecdotal/recap/semester?classId=${classId ?? ""}`}>Rekap semester</a></div><div class="space-y-2">{records.map((record) => <a href={`/app/journal/anecdotal/${record.id}/edit`} class="gt-card p-4 block"><div class="flex justify-between gap-2"><p class="font-medium">{record.student.name} <span class="gt-muted font-normal">({record.student.class.name})</span></p><span class={record.category === "positive" ? "gt-badge-emerald" : "gt-badge-amber"}>{record.category === "positive" ? "Positif" : "Perlu bimbingan"}</span></div><p class="text-sm mt-1">{record.description}</p><p class="gt-muted text-xs mt-2">{record.eventDate} · {record.values.map((v) => v.visionValue.name).join(", ")}</p></a>)}{records.length === 0 && <p class="gt-muted text-center py-8">Belum ada catatan pada periode ini.</p>}</div></Layout>);
});

anecdotalRoutes.get("/app/journal/anecdotal/new", async (c) => { const user = c.get("user"); const classId = Number(c.req.query("classId")); const [classes, students, values] = await Promise.all([listTeachingClasses(user.id), classId ? listActiveStudentsForTeacher(user.id, classId) : [], listVisionValues()]); return c.html(<Layout title="Catatan Baru" user={user} activeNav="journal"><JournalTabs active="anecdotal" /><h1 class="text-xl font-semibold mb-4">Catatan observasi baru</h1><RecordForm action="/app/journal/anecdotal" classes={classes} students={students} values={values} /></Layout>); });

anecdotalRoutes.post("/app/journal/anecdotal", async (c) => { const user = c.get("user"); const body = await c.req.parseBody(); const category = str(body.category); const record = (category === "positive" || category === "needs_guidance") ? await createRecord(user.id, { studentId: Number(body.studentId), eventDate: str(body.eventDate) || todayIso(), eventTime: str(body.eventTime), location: str(body.location), description: str(body.description), category, followUpNotes: str(body.followUpNotes), visionValueIds: ids(body.visionValueIds) }) : null; return record ? c.redirect("/app/journal/anecdotal") : c.text("Data tidak valid atau kelas/murid tidak diizinkan.", 400); });

anecdotalRoutes.get("/app/journal/anecdotal/:id/edit", async (c) => { const user = c.get("user"); const record = await getRecordForTeacher(user.id, Number(c.req.param("id"))); if (!record) return c.redirect("/app/journal/anecdotal"); const [classes, students, values] = await Promise.all([listTeachingClasses(user.id), listActiveStudentsForTeacher(user.id, record.student.classId), listVisionValues()]); return c.html(<Layout title="Edit Catatan" user={user} activeNav="journal"><JournalTabs active="anecdotal" /><h1 class="text-xl font-semibold mb-4">Edit catatan</h1><RecordForm action={`/app/journal/anecdotal/${record.id}`} classes={classes} students={students} values={values} record={record} /><form method="post" action={`/app/journal/anecdotal/${record.id}/delete`} class="mt-3"><button class="gt-subtle text-sm">Hapus catatan</button></form></Layout>); });

anecdotalRoutes.post("/app/journal/anecdotal/:id", async (c) => { const user = c.get("user"); const body = await c.req.parseBody(); const category = str(body.category); const ok = (category === "positive" || category === "needs_guidance") && await updateRecord(user.id, Number(c.req.param("id")), { eventDate: str(body.eventDate) || todayIso(), eventTime: str(body.eventTime), location: str(body.location), description: str(body.description), category, followUpNotes: str(body.followUpNotes), visionValueIds: ids(body.visionValueIds) }); return ok ? c.redirect("/app/journal/anecdotal") : c.text("Data tidak valid.", 400); });
anecdotalRoutes.post("/app/journal/anecdotal/:id/delete", async (c) => (await deleteRecord(c.get("user").id, Number(c.req.param("id")))) ? c.redirect("/app/journal/anecdotal") : c.text("Tidak ditemukan.", 404));

anecdotalRoutes.get("/app/journal/anecdotal/recap/monthly", async (c) => { const user = c.get("user"); const classId = Number(c.req.query("classId")); const month = c.req.query("month") || todayIso().slice(0, 7); const [classes, recap] = await Promise.all([listTeachingClasses(user.id), classId ? monthlyRecap(user.id, classId, month) : []]); return c.html(<Layout title="Rekap Bulanan" user={user} activeNav="journal"><JournalTabs active="anecdotal" /><h1 class="text-xl font-semibold mb-4">Rekap bulanan</h1><form method="get" class="grid grid-cols-2 gap-2 mb-4"><select name="classId" required class="gt-input">{classes.map((item) => <option value={item.id} selected={item.id === classId}>{item.name}</option>)}</select><input name="month" type="month" value={month} class="gt-input" /><button class="gt-btn-primary col-span-2">Tampilkan</button></form><div class="space-y-2">{recap.map((row) => <div class="gt-card p-3"><p class="font-medium">{row.studentName} · {row.visionValueName}</p><p class="gt-muted text-sm">Positif: {row.positiveCount} · Perlu bimbingan: {row.needsGuidanceCount}</p></div>)}</div></Layout>); });

anecdotalRoutes.get("/app/journal/anecdotal/recap/semester", async (c) => { const user = c.get("user"); const classes = await listTeachingClasses(user.id); const classId = Number(c.req.query("classId")) || classes[0]?.id; const academicYear = c.req.query("academicYear") || classes.find((item) => item.id === classId)?.academicYear || `${new Date().getFullYear()}/${new Date().getFullYear() + 1}`; const semester = c.req.query("semester") || "1"; const recap = classId ? await semesterRecap(user.id, classId, semester, academicYear) : null; return c.html(<Layout title="Rekap Semester" user={user} activeNav="journal"><JournalTabs active="anecdotal" /><h1 class="text-xl font-semibold mb-4">Rekap semester</h1><form method="get" class="grid grid-cols-3 gap-2 mb-4"><select name="classId" class="gt-input">{classes.map((item) => <option value={item.id} selected={item.id === classId}>{item.name}</option>)}</select><select name="semester" class="gt-input"><option value="1" selected={semester === "1"}>Sem. 1</option><option value="2" selected={semester === "2"}>Sem. 2</option></select><input name="academicYear" value={academicYear} class="gt-input" /><button class="gt-btn-primary col-span-3">Tampilkan</button></form>{recap && <><div class="grid grid-cols-3 gap-2 mb-4"><div class="gt-card p-3 text-center"><b>{recap.totalRecords}</b><p class="gt-muted text-xs">Catatan</p></div><div class="gt-card p-3 text-center"><b>{recap.observedPercent}%</b><p class="gt-muted text-xs">Murid teramati</p></div><div class="gt-card p-3 text-center"><b>{recap.observedStudents}</b><p class="gt-muted text-xs">dari {recap.rows.length} murid</p></div></div><div class="space-y-3">{recap.rows.map((row) => <div class="gt-card p-3"><p class="font-medium mb-2">{row.student.name}</p><div class="space-y-2">{row.values.map((value) => <details class="text-sm"><summary><span class="gt-muted">{value.visionValue.name}: </span><b class="gt-accent-text">{value.developmentCategory}</b><span class="gt-muted"> ({value.positiveCount}+/ {value.needsGuidanceCount}-)</span></summary><form method="post" action="/app/journal/anecdotal/recap/narrative" class="mt-2"><input type="hidden" name="studentId" value={row.student.id} /><input type="hidden" name="visionValueId" value={value.visionValue.id} /><input type="hidden" name="semester" value={semester} /><input type="hidden" name="academicYear" value={academicYear} /><input type="hidden" name="classId" value={classId} /><textarea name="narrativeDescription" rows={2} class="gt-input" placeholder="Narasi laporan (opsional)">{value.narrativeDescription ?? ""}</textarea><button class="gt-btn-secondary text-xs mt-1">Simpan narasi</button></form></details>)}</div></div>)}</div></>}</Layout>); });

anecdotalRoutes.post("/app/journal/anecdotal/recap/narrative", async (c) => { const body = await c.req.parseBody(); const semester = str(body.semester); const academicYear = str(body.academicYear); const classId = Number(body.classId); await saveNarrative(c.get("user").id, Number(body.studentId), Number(body.visionValueId), semester, academicYear, str(body.narrativeDescription)); return c.redirect(`/app/journal/anecdotal/recap/semester?classId=${classId}&semester=${encodeURIComponent(semester)}&academicYear=${encodeURIComponent(academicYear)}`); });

// API JSON untuk integrasi/klien lain.
anecdotalRoutes.get("/api/anecdotal-records", async (c) => c.json(await listRecords(c.get("user").id, { classId: Number(c.req.query("classId")) || undefined, month: c.req.query("month") })));
anecdotalRoutes.post("/api/anecdotal-records", async (c) => { const body = await c.req.json(); const category = str(body.category); const record = (category === "positive" || category === "needs_guidance") ? await createRecord(c.get("user").id, { studentId: Number(body.studentId), eventDate: str(body.eventDate) || todayIso(), eventTime: str(body.eventTime), location: str(body.location), description: str(body.description), category, followUpNotes: str(body.followUpNotes), visionValueIds: ids(body.visionValueIds) }) : null; return record ? c.json(record, 201) : c.json({ error: "Data tidak valid atau tidak diizinkan" }, 400); });
anecdotalRoutes.put("/api/anecdotal-records/:id", async (c) => { const body = await c.req.json(); const category = str(body.category); const ok = (category === "positive" || category === "needs_guidance") && await updateRecord(c.get("user").id, Number(c.req.param("id")), { eventDate: str(body.eventDate) || todayIso(), eventTime: str(body.eventTime), location: str(body.location), description: str(body.description), category, followUpNotes: str(body.followUpNotes), visionValueIds: ids(body.visionValueIds) }); return ok ? c.json({ ok: true }) : c.json({ error: "Data tidak valid atau tidak ditemukan" }, 400); });
anecdotalRoutes.delete("/api/anecdotal-records/:id", async (c) => (await deleteRecord(c.get("user").id, Number(c.req.param("id")))) ? c.body(null, 204) : c.json({ error: "Tidak ditemukan" }, 404));
anecdotalRoutes.get("/api/anecdotal-records/recap/monthly", async (c) => c.json(await monthlyRecap(c.get("user").id, Number(c.req.query("classId")), c.req.query("month") || todayIso().slice(0, 7))));
anecdotalRoutes.get("/api/anecdotal-records/recap/semester", async (c) => c.json(await semesterRecap(c.get("user").id, Number(c.req.query("classId")), c.req.query("semester") || "1", c.req.query("academicYear") || `${new Date().getFullYear()}/${new Date().getFullYear() + 1}`)));
